spring:
  application:
    name: bear-converter
  servlet:
    multipart:
      max-file-size: ${PDF_MAX_FILE_SIZE:10MB}
      max-request-size: ${PDF_MAX_REQUEST_SIZE:10MB}
  datasource:
    url: jdbc:postgresql://${DATABASEHOST:localhost}:${DATABASEPORT:5432}/${DATABASENAME}
    username: ${DATABASEUSERNAME}
    password: ${DATABASEPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

security:
  jwt:
    access-token-minutes: ${JWT_ACCESS_TOKEN_MINUTES:15}
    refresh-token-days: ${JWT_REFRESH_TOKEN_DAYS:7}
    refresh-token-cleanup-delay-ms: ${JWT_REFRESH_TOKEN_CLEANUP_DELAY_MS:3600000}
    private-key: ${JWT_PRIVATE_KEY:}
    public-key: ${JWT_PUBLIC_KEY:}
